# Generated by Django 4.1.7 on 2023-04-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_alter_task_options_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
