# Generated by Django 4.1.7 on 2023-04-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('AD', 'admin'), ('ST', 'staff'), ('CU', 'customer')], default='CU', max_length=2),
        ),
    ]
